### ISSUE TITLE
Checking "Send email to new user" checkbox causes persona bar page to blank

### ISSUE THREAD

**Issue by Icidis** [dnnsoftware/Dnn.AdminExperience#356]
## Description of bug
When trying to register a new user, checking the "Send email to new user" checkbox the persona bar 'Add user' page disappears (Blank white page) and you cannot continue with the user creation.

Please note that this was not an upgrade but a **new install**.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Manage -> Users
2. Click on 'Add user'
3. Fill in user details
4. Check 'Send email to new user' checkbox.

## Current result
Persona bar page goes blank.

## Expected result
Page to not go blank.

## Screenshots
![dnn_93_blank_page](https://user-images.githubusercontent.com/1651587/51595359-379c6180-1eff-11e9-989c-5299ecaccb37.jpg)

## Error log
Javascript console error log:

`export-bundle.js?cdv=52:90 ReferenceError: props is not defined
    at Checkbox.value (export-bundle.js?cdv=52:1)
    at Si (export-bundle.js?cdv=52:90)
    at xi (export-bundle.js?cdv=52:90)
    at Pi (export-bundle.js?cdv=52:90)
    at Ri (export-bundle.js?cdv=52:90)
    at Cn (export-bundle.js?cdv=52:90)
ga @ export-bundle.js?cdv=52:90
n.callback @ export-bundle.js?cdv=52:90
_o @ export-bundle.js?cdv=52:90
co @ export-bundle.js?cdv=52:90
Si @ export-bundle.js?cdv=52:90
xi @ export-bundle.js?cdv=52:90
Pi @ export-bundle.js?cdv=52:90
Ri @ export-bundle.js?cdv=52:90
Cn @ export-bundle.js?cdv=52:90

export-bundle.js?cdv=52:1 Uncaught ReferenceError: props is not defined
    at Checkbox.value (export-bundle.js?cdv=52:1)
    at Si (export-bundle.js?cdv=52:90)
    at xi (export-bundle.js?cdv=52:90)
    at Pi (export-bundle.js?cdv=52:90)
    at Ri (export-bundle.js?cdv=52:90)
    at Cn (export-bundle.js?cdv=52:90)
value @ export-bundle.js?cdv=52:1
Si @ export-bundle.js?cdv=52:90
xi @ export-bundle.js?cdv=52:90
Pi @ export-bundle.js?cdv=52:90
Ri @ export-bundle.js?cdv=52:90
Cn @ export-bundle.js?cdv=52:90
`

With Microsoft Edge, the personna bar manage user's page does not even show up. It also shows a blank page with the following in the console.

`SCRIPT1028: SCRIPT1028: Expected identifier, string or number - index.html (20,60863)`

## Additional context
I was testing the "Email problem when creating new users" as per the following pull requests:

**Dnn.AdminExperience:** #174 
**Dnn.Platform:** dnnsoftware/Dnn.Platform#2424

## Affected version

* [x] 9.3.0-rc0

## Affected browser

* [X] Chrome 71.0.3578.98
* [X] Firefox 64.0.2
* [ ] Safari
* [ ] Internet Explorer
* [X] Edge (See below comments)

**Comment by valadas** [comment]
This should now be fixed after https://github.com/dnnsoftware/Dnn.React.Common/pull/203, can you try it on build 9018 available here https://dotnet.visualstudio.com/DNN/_build/results?buildId=9018
Click on Artifacts on top right and download that installer.

Please confirm if that works fine after, RC1 should be coming shortly...

**Comment by Icidis** [comment]
The 9018 build seems to fix this issue. Please close this specific issue. But the user registration email is still not working.

**Comment by valadas** [comment]
Cool, closing this one since there is another issue for the actual sending of the email. Thanks @Icidis
